# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields
import swapper

class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0005_auto_20151019_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategoryblogpage',
            options={
            },
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_pages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='blog_categories',
            field=models.ManyToManyField(blank=True, through=swapper.get_model_name('blog', 'BlogCategoryBlogPage'), to=settings.BLOG_BLOGCATEGORY_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='body'),
        ),
    ]
